### ISSUE TITLE
"GNU git" in README feels slightly misleading

### ISSUE THREAD

**Issue by asiekierka** [khanzf/opengit#5]
While, in context, the name clearly refers to the version control system "Git", "GNU GIT" could actually refer to an [old 1998-1999](https://www.gnu.org/software/git/) GNU project which was supposed to add interactive tools. The name is reserved to this day.

I'd say "GPL git" or "GPL-licensed git" would be slightly less misleading, as it ensures the intention is to highlight the license rather than describe it as a GNU project.

Maybe I'm being a bit too pedantic, though.

**Comment by khanzf** [comment]
Pardon the long delay.
Please see commits fe5c6880c09a78c7ad61c2ceed46d47e82f51340 and 3911d10fc218112e1c65bfc4ee302aa62d37af72.
